version: '3.8'

volumes:
  composer-vol:
services:
  web:
    build: .  
    container_name: web-dashboard-api
    restart: unless-stopped
    volumes:
      - './public:/var/www/html'
      - './:/var/www/'
    ports:
      - 82:80
    networks:
          - ptpn-database_default
networks:
  ptpn-database_default:
    external: true